swagger: "2.0"
info:
  version: "1.0.0"
  title: "Bibbox"
basePath: "/api/v1"
tags:
  - name: "apps"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /apps:
    get:
      tags:
        - "apps"
      summary: "Get all available apps"
      operationId: "listApps"
      responses:
        200:
          description: "Successfully retrived list"
          schema:
            $ref: "#/definitions/list"
        404:
          description: "Could not load list"
      x-swagger-router-controller: "web.controllers.bibbox_controller"
  /installedapps:
    get:
      tags:
        - "installed apps"
      summary: "Get all installed apps"
      operationId: "listInstalledApps"
      responses:
        200:
          description: "Successfully retrived list"
          schema:
            $ref: "#/definitions/list"
        404:
          description: "Could not load list"
      x-swagger-router-controller: "web.controllers.bibbox_controller"
  /startapp/{instanceName}:
    get:
      tags:
        - "start app"
      summary: "Starts specific app"
      operationId: "startApp"
      parameters:
        - name: "instanceName"
          in: "path"
          description: "start an app"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully started app"
          schema:
            $ref: "#/definitions/string"
        404:
          description: "Could not start app"
      x-swagger-router-controller: "web.controllers.bibbox_controller"

  /stopapp/{instanceName}:
    get:
      tags:
        - "stop app"
      summary: "Starts specific app"
      operationId: "stopApp"
      parameters:
        - name: "instanceName"
          in: "path"
          description: "stop an app"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully stopped app"
          schema:
            $ref: "#/definitions/string"
        404:
          description: "Could not stop app"
      x-swagger-router-controller: "web.controllers.bibbox_controller"

  /removeapp/{instanceName}:
    get:
      tags:
        - "remove app"
      summary: "removes specific app"
      operationId: "removeApp"
      parameters:
        - name: "instanceName"
          in: "path"
          description: "remove an app"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully removed app"
          schema:
            $ref: "#/definitions/string"
        404:
          description: "Could not remove app"
      x-swagger-router-controller: "web.controllers.bibbox_controller"

definitions:
  list:
    type: string
  string:
    type: string


