version: '3'

networks:
    bibbox-default-network:
      external: true


services:
  nginx: 
    image: nginx:latest
    container_name: local_nginx
    volumes:
      - ./sys-proxy/proxyconfig:/etc/nginx/conf.d
    ports:
      - "8010:80"
    networks:
      - bibbox-default-network
